config/routes.rb
Rails.application.routes.draw do

  resources :neighborhoods
  root 'neighborhoods#index'

end

#            Prefix Verb   URI Pattern                       Controller#Action
#     neighborhoods GET    /neighborhoods(.:format)          neighborhoods#index
#                   POST   /neighborhoods(.:format)          neighborhoods#create
#  new_neighborhood GET    /neighborhoods/new(.:format)      neighborhoods#new
# edit_neighborhood GET    /neighborhoods/:id/edit(.:format) neighborhoods#edit
#      neighborhood GET    /neighborhoods/:id(.:format)      neighborhoods#show
#                   PATCH  /neighborhoods/:id(.:format)      neighborhoods#update
#                   PUT    /neighborhoods/:id(.:format)      neighborhoods#update
#                   DELETE /neighborhoods/:id(.:format)      neighborhoods#destroy
#              root GET    /                                 neighborhoods#index

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  validates :name, presence: true
  validates :nickname, presence: true
  validates :population, presence: true
  validates :borough, presence: true
  validates :description, presence: true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ":style/brooklyn_nabes.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]

  # show all neighborhoods (get request)
  def index
    @neighborhoods = Neighborhood.order(:name).all
  end

  # show the form to create a new neighborhood (get request)
  def new
    @neighborhood = Neighborhood.new
  end

  # CREATE! a new neighborhood (post request)
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)
    if @neighborhood.save
      redirect_to @neighborhood
    else
      redirect_to neighborhoods_path
      # render :new
    end
  end

  # show the form to update a neighborhood (get request)
  def edit
  end

  # edit/modify/update a neighborhood (put request)
  def update
    @neighborhood.update_attributes(neighborhood_params)
    if @neighborhood.save
      redirect_to @neighborhood
    else
      redirect_to neighborhoods_path
    end
  end

  # show an individual neighborhood (get request)
  def show
  end

  # delete an individual neighborhood (delete request)
  def destroy
    @neighborhood.destroy
    redirect_to neighborhoods_path
  end

  private

  def set_neighborhood
    @neighborhood = Neighborhood.find(params[:id])
  end

  def neighborhood_params
    params.require(:neighborhood).permit(:name, :nickname, :borough, :description, :population, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neighborhoods</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Dosis:400,600' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id="wrapper">
    <div id="header">
      <p id="hello">Hello ❤</p>
      <%= image_tag "brooklyn.png", alt: "brooklyn", id: "logo" %>
    </div>

    <div id="content">
      <%= yield %>
    </div>

    <footer>
      <p id="footer-text">< CODED IN BROOKLYN BY MALINA /></p>
    </footer>
  </div>
  
</body>
</html>

app/views/neighborhoods/_form.html.erb
<div class="form-container">
  <%= form_for @neighborhood, html: { multipart: true } do |form| %>
    
    <table>
      <tr>
        <td class="property">Name:</td>
        <td class="value"><%= form.text_field :name %></td>
      </tr>
      <tr>
        <td class="property">Nickname:</td>
        <td class="value"><%= form.text_field :nickname %></td>
      </tr>
      <tr>
        <td class="property">Population:</td>
        <td class="value"><%= form.text_field :population %></td>
      </tr>
      <tr>
        <td class="property">Borough:</td>
        <td class="value"><%= form.text_field :borough %><br></td>
      </tr>
    </table><br>
    Description:<br>
    <%= form.text_area :description, class:"description-field" %>
    <%= form.file_field :image %>
    <br><br>
    <div id="button-container2">
      <%= link_to '&lt; HOME'.html_safe, neighborhoods_path, class: "action-link" %>
      <%= form.submit 'SAVE &gt;'.html_safe, class:"submit-button" %>
    </div>
  <% end %>
</div>

app/views/neighborhoods/edit.html.erb
<h2>Edit a neighborhood:</h2>

<%= render :partial => 'form' %>

app/views/neighborhoods/index.html.erb
<h3>Check out my favorite neighborhoods:</h3>
<% @neighborhoods.each do |nabe| %>
  <div class="card-container1"> 
    <div class="title-container">
      <p class="name"><%= nabe.name %></p>
      <%= link_to '&gt;'.html_safe, neighborhood_path(nabe.id), class: "expand-link" %>
    </div>
  </div>
<% end %>
<h3><%= link_to '+ ADD A NEIGHBORHOOD', new_neighborhood_path, class: "action-link" %></h3>

app/views/neighborhoods/new.html.erb
<h2>Create a neighborhood:</h2>

<%= render :partial => 'form' %>

app/views/neighborhoods/show.html.erb
<h1><span class="name-headline"><%= @neighborhood.name %></span></h1>
<div class="card-container2">
  <div class="left-container"> 
    <%= image_tag @neighborhood.image.url(:medium), class: "image" %>
  </div>
  <div class="right-container">
    <div class="text-container2">
      They call me <strong><%= @neighborhood.nickname %></strong>.<br>
      Home to <strong><%= @neighborhood.population %></strong> New Yorkers.<br>
      Located in <strong><%= @neighborhood.borough %></strong>.<br>
      <%= @neighborhood.description %>
    </div>
    <span class="button-container">
      <%= link_to '&lt; HOME'.html_safe, neighborhoods_path, class: "action-link" %>
      <%= link_to 'EDIT', edit_neighborhood_path(@neighborhood.id), class: "action-link" %>
      <%= link_to 'DELETE &gt;'.html_safe, @neighborhood, method: 'delete', data: { confirm: "Are you sure?" }, class: "action-link" %>
    </span>
  </div>
</div>